[phases.setup]
nixPkgs = ['php81', 'nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci --only=production'
]

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'npm run build'
]

[start]
cmd = 'composer run start'

[variables]
PHP_SERVER_INDEX = 'public/index.php'