[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["php", "php81Extensions.pdo_mysql", "php81Extensions.gd"]
